### ISSUE TITLE
No data.mat existing?

### ISSUE THREAD

**Issue by zhangqizky** [remega/LEDOV-eye-tracking-database#2]
Hello PhD Jiang!
_there is a code_ load(['./' InputVideoName_short '/Data.mat'],'Data') _in the demo.m_ 
but I can not find it??so the demo can not run correctly....
Thanks for answering...

**Comment by remega** [comment]
Thanks for your interest.
Have you downloaded the whole database from the online drive?

**Comment by zhangqizky** [comment]
师兄你好！我就不说英文了啊！我给你北航邮箱发了邮件，那个百度云上的视频我下载了很长时间还没下载成功...

**Comment by remega** [comment]
我邮件上回复你啦
