### ISSUE TITLE
Could you share your exact split of dataset?

### ISSUE THREAD

**Issue by kylemin** [remega/LEDOV-eye-tracking-database#3]
In your paper, you split the dataset into 456, 41, 41 videos. Could you share the exact split information?

**Comment by remega** [comment]
The information is shown in namelist.mat

**Comment by kylemin** [comment]
Thanks. So you used 461, 36, 41 splits, rather than 456, 41, 41, right?
This is important because I want to replicate your exact training and testing setting.

**Comment by remega** [comment]
Yes, actually, we used 461 videos as the training set.

**Comment by kylemin** [comment]
Thank you for your kindness.
