### ISSUE TITLE
Is there any reason you used W=80 to blur the fixation map?

### ISSUE THREAD

**Issue by kylemin** [remega/LEDOV-eye-tracking-database#4]
Or, is there any specific reason like W=80 is 1.5 or 3 degree of visual angle?

**Comment by remega** [comment]
Yes, W=40 * 2 here equals to 1.5 visual angle, according to our eye-tracking experiment (distance between subject and display, resolution of display). That means we assume that the guassian mask would decrease to half max at 1.5 visual angle.
