### ISSUE TITLE
Dropbox zipfile corrupt

### ISSUE THREAD

**Issue by Linardos** [remega/LEDOV-eye-tracking-database#7]
I used wget to download on a Linux server from Dropbox, but I get the following error when trying to unzip the file:

```
Archive:  LEDOV002.zip
fatal error: read failure while seeking for End-of-centdir-64 signature.
  This zipfile is corrupt.
unzip:  cannot find zipfile directory in one of LEDOV002.zip or
        LEDOV002.zip.zip, and cannot find LEDOV002.zip.ZIP, period.
```

It looks like the file on Dropbox is corrupt?

**Comment by remega** [comment]
Hi, I guess you should merge 2 zip parts into one first, and then unzip it. 
Actually, the filenames in Dropbox are LEDOV.zip.001 and LEDOV.zip.002, I don't if the names changed when using wget. In that case, one should follows
cat LEDOV.zip* > lEDOV.zip
unzip LEDOV.zip 
to get the data.

**Comment by Linardos** [comment]
Hmm, unfortunately this doesn't seem to work. Here is the whole pipeline:

```
wget https://www.dropbox.com/s/xqrae7bc73jnncr/LEDOV.zip.001
wget https://www.dropbox.com/s/xqrae7bc73jnncr/LEDOV.zip.002
cat LEDOV.zip.00* > LEDOV.zip
unzip LEDOV.zip
Archive:  LEDOV.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of LEDOV.zip or
        LEDOV.zip.zip, and cannot find LEDOV.zip.ZIP, period.
```

**Comment by remega** [comment]
You are right. I am sorry for the problem of the zip files. I am re-comressing them again, and I will uploard to Dropbox ASAP.

**Comment by Linardos** [comment]
That is alright. Let me know when the corrected file is uploaded; I am quite eager to test my model on this dataset. Cheers.

**Comment by remega** [comment]
Thanks for waiting, the updated link is https://www.dropbox.com/s/pc8symd9i3cky1q/LEDOV.zip?dl=0.

**Comment by Linardos** [comment]
It works now. Thanks!
